version: "1.0.3"
name: MailtoLink
description: Create mailto links with ease
url: https://github.com/marsvogel/statamic-mailto
developer: Christopher Bischoff
developer_url: https://github.com/marsvogel
